services:
  php:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: enso
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - 8000:80
    volumes:
      - ./docker/vhosts.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./:/var/www/html
    environment:
      DB_HOST: mysqldb
      REDIS_HOST: redis
    env_file:
      - .env
    depends_on:
      mysqldb:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - enso

  mysqldb:
    image: mysql:8
    container_name: enso-mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', '127.0.0.1', '-proot']
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - enso

  redis:
    image: redis:latest
    container_name: enso-redis
    restart: unless-stopped
    networks:
      - enso

#  myadmin:
#    image: phpmyadmin/phpmyadmin:4.7
#    container_name: enso-phpmyadmin
#    ports:
#      - 8081:80
#    environment:
#      - PMA_ARBITRARY=1
#      - PMA_HOST=enso-${DB_CONNECTION}
#    restart: always
#    depends_on:
#      - mysqldb

networks:
  enso:

volumes:
  mysql_data:
